Repository rayhogan/planningpoker, pull requests merged in 2020-10, with the labels that each got.

#2 Create project skeleton
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest-accepted

#4 Added basic poker UI
  public/assets/github.svg
  public/assets/linkedin.svg
  public/assets/twitter.svg
  public/index.html
  public/styles/poker.css
Labels: hacktoberfest-accepted

#6 Showconnections
  README.md
  public/assets/screenshot.png
  public/index.html
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest-accepted

#8 Storytitleupdate
  public/index.html
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest-accepted

#9 Uienhancements
  public/assets/linkedin.svg
  public/assets/twitter.svg
  public/styles/poker.css
Labels: hacktoberfest-accepted

#11 Changeusername
  README.md
  public/assets/screenshot.png
  public/index.html
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#13 Uservoting
  README.md
  public/assets/screenshot.png
  public/index.html
  public/scripts/engine.js
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#15 Showscore
  public/index.html
  public/scripts/engine.js
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#18 Allow users to create a backlog of stories.
  public/index.html
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#20 Privatesessions
  README.md
  public/assets/screenshot.png
  public/assets/screenshot_2.png
  public/index.html
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#23 Remove unused logic.
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#24 Extend null check to look for empty strings when submitting user and room names
  public/scripts/engine.js
Labels: hacktoberfest, hacktoberfest-accepted

#25 Allow users to delete stories
  public/scripts/engine.js
  public/styles/poker.css
  server.js
Labels: hacktoberfest

#27 Fixed score calc and additional error handling
  server.js
Labels: hacktoberfest, hacktoberfest-accepted
